// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import { Field } from '@grafana/data';
import * as common from '@grafana/schema';

export enum PointShape {
  Circle = 'circle',
  Square = 'square',
}

export enum SeriesMapping {
  Auto = 'auto',
  Manual = 'manual',
}

export enum XYShowMode {
  Lines = 'lines',
  Points = 'points',
  PointsAndLines = 'points+lines',
}

export interface MatcherConfig {
  id: string;
  options?: unknown;
}

export const defaultMatcherConfig: Partial<MatcherConfig> = {
  id: '',
};

export interface FieldConfig extends common.HideableFieldConfig, common.AxisConfig {
  fillOpacity?: number;
  lineStyle?: common.LineStyle;
  lineWidth?: number;
  pointShape?: PointShape;
  pointSize?: {
    fixed?: number;
    min?: number;
    max?: number;
  };
  pointStrokeWidth?: number;
  show?: XYShowMode;
}

export const defaultFieldConfig: Partial<FieldConfig> = {
  fillOpacity: 50,
  show: XYShowMode.Points,
};

export interface XYSeriesConfig {
  color?: {
    matcher: MatcherConfig;
  };
  frame?: {
    matcher: MatcherConfig;
  };
  name?: {
    fixed?: string;
  };
  size?: {
    matcher: MatcherConfig;
  };
  x?: {
    matcher: MatcherConfig;
  };
  y?: {
    matcher: MatcherConfig;
  };
}

export interface Options extends common.OptionsWithLegend, common.OptionsWithTooltip {
  mapping: SeriesMapping;
  series: XYSeriesConfig[];
  yField?: string;
  xFields?: string[];
  frame?: number;
}

export const defaultOptions: Partial<Options> = {
  series: [],
};
// --- (Fim do código nativo reaproveitado) ---


// ===================================================================
// --- INÍCIO DAS NOSSAS MODIFICAÇÕES ---
// ===================================================================

/**
 * ADIÇÃO: Esta é a nossa interface de configuração customizada.
 * Ela é usada pelo 'ManualSeriesEditor.tsx' e salva os dados
 * da nossa configuração 1:1 (X/Y) simples.
 */
export interface ManualSeriesConfig {
  name?: string;
  yField?: string;
  xField?: string;
  color?: string;
  isLimit?: boolean;
}

/**
 * ADIÇÃO: Usamos "declaration merging" do TypeScript para
 * injetar a nossa lista 'manualSeries' na interface 'Options'
 * principal do painel.
 */
declare module './panelcfg.gen' {
  interface Options {
    manualSeries?: ManualSeriesConfig[];
  }
}

/**
 * MODIFICAÇÃO: Esta é a nossa interface interna (materializada) da série.
 * Ela foi simplificada (em relação à nativa) para se alinhar com
 * a nossa lógica 1:1 e com o que 'prepConfig.ts' espera.
 */
export interface XYSeries {
  name: string;
  x: { field: Field };
  y: { field: Field };
  color: { field?: Field; fixed?: string };
  isLimit?: boolean;
  size: { field?: import('@grafana/data').Field; fixed?: number; min?: number; max?: number };
  showLine: boolean;
  lineWidth: number;
  lineStyle: any;
  showPoints: string;
  pointShape: string;
  pointStrokeWidth: number;
  fillOpacity: number;
}

/**
 * ADIÇÃO: Interface de dados para o nosso tooltip customizado.
 * Recebe os dados do estado 'tooltip' no 'VerticalXYPanel'.
 */
export interface TooltipData {
  seriesName: string;
  xValue: string;
  yValue: string;
  xPos: number; // Posição X (esquerda) vinda do uPlot
  yPos: number; // Posição Y (topo) vinda do uPlot
}
